//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaultTrage_Test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fault
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fault()
        {
            this.ImpactInfoes = new HashSet<ImpactInfo>();
        }
    
        public int FaultId { get; set; }
        public int FaultType { get; set; }
        public string FaultSeverity { get; set; }
        public string FaultComponent { get; set; }
        public System.DateTime FaultEventDate { get; set; }
        public int SLA { get; set; }
        public string FaultPlatform { get; set; }
        public string FaultImpact { get; set; }
        public int TicketStatus { get; set; }
        public double FaultEscalationTime { get; set; }
    
        public virtual SLA SLA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpactInfo> ImpactInfoes { get; set; }
    }
}
