//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaultTrage_Test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketStatu()
        {
            this.ImpactInfoes = new HashSet<ImpactInfo>();
        }
    
        public int TicketStausId { get; set; }
        public string TicketStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpactInfo> ImpactInfoes { get; set; }
        public virtual TicketStatu TicketStatus1 { get; set; }
        public virtual TicketStatu TicketStatu1 { get; set; }
    }
}
